package com.auth.ekyc.ekyc_backend.domain.enums;

public enum ActionType {

    USER_REGISTERED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,

    EMAIL_VERIFIED,
    VERIFICATION_RESENT,

    PROFILE_CREATED,
    PROFILE_UPDATED,
    ADDRESS_UPDATED,

    KYC_STARTED,
    KYC_SUBMITTED,
    KYC_PRECHECK_FAILED,
    KYC_SENT_TO_PROVIDER,

    PROVIDER_ACK_RECEIVED,
    PROVIDER_RESULT_RECEIVED,

    KYC_AUTO_APPROVED,
    KYC_AUTO_REJECTED,
    KYC_MANUAL_REVIEW_REQUIRED,

    ADMIN_APPROVED_KYC,
    ADMIN_REJECTED_KYC,
    KYC_RETRY_REQUESTED
}